param(
    [string]$CsvPath = "$PSScriptRoot\..\data\checkpoints.csv",
    [string]$OutputPath = "$PSScriptRoot\..\source\CheckpointConfig.mc"
)

$csvLines = Get-Content -LiteralPath $CsvPath -Encoding UTF8 | Where-Object { $_.Trim().Length -gt 0 }
$csvLines = @($csvLines)
$headerOnly = $csvLines.Count -le 1
$firstLine = $csvLines[0]
$isTabSeparated = ($csvLines | Where-Object { $_ -like "*`t*" }).Count -gt 0
if ($isTabSeparated) {
    # Google Sheets may paste tab-separated rows below an existing comma
    # separated header. Normalize that header before parsing.
    if ($firstLine -notlike "*`t*" -and $firstLine -like "*,*") {
        $csvLines[0] = $firstLine.Replace(',', "`t")
    }
    $rows = $csvLines | ConvertFrom-Csv -Delimiter "`t"
} else {
$rows = if ($headerOnly) { @() } else { $csvLines | ConvertFrom-Csv -Delimiter "," }
}
$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("module CheckpointConfig {")
$lines.Add("    // Generated from data/checkpoints.csv. Do not edit this file directly.")
$lines.Add("    const CHECKPOINTS = [")

for ($i = 0; $i -lt $rows.Count; $i++) {
    $row = $rows[$i]
    $escapedName = $row.name.Replace('\', '\\').Replace('"', '\"')
    $serialized = ('builtin-{0}|{1}|{2}|{3}|{4}|{5}' -f $i, $escapedName, $row.latitude, $row.longitude, $row.triggerRadiusMeters, $row.rearmRadiusMeters)
    $comma = if ($i -lt $rows.Count - 1) { ',' } else { '' }
    $lines.Add(('        "{0}"{1}' -f $serialized, $comma))
}

$lines.Add("    ];")
$lines.Add("}")
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($OutputPath, ($lines -join "`r`n"), $utf8NoBom)
Write-Host "Generated $OutputPath from $CsvPath"
